//Product types
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

//Category types
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

//selected category products
export const FETCH_SELECTED_CATEGORY_PRODUCT_REQUEST =
  "FETCH_SELECTED_CATEGORY_PRODUCT_REQUEST";
export const FETCH_SELECTED_CATEGORY_PRODUCT_SUCCESS =
  "FETCH_SELECTED_CATEGORY_PRODUCT_SUCCESS";
export const FETCH_SELECTED_CATEGORY_PRODUCT_FAILURE =
  "FETCH_SELECTED_CATEGORY_PRODUCT_FAILURE";
